// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/honeycombauth component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("honeycombauth")
	ScopeName = "github.com/honeycombio/honeycomb-auth-extension/honeycombauthextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
